# 1. Py Torch Basics
### 1.1. Bascis Functions
- `.size()`:
- `.item()`: to get 1 element from Tensor
- Reshape: `.view()`
    ```Python
    # Reshape with torch.view()
    x = torch.randn(4, 4)
    y = x.view(16)     # resize 2-D (4,4) to 1-D (16)
    z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
    # if -1 it pytorch will automatically determine the necessary size
    print(x.size(), y.size(), z.size())
    ```

### 1.2. Inplace Operation for Tensors
- In Pytorch, function followed by `_` means inplace-operation
- `y.add_(x)`: will add x to y

### 1.3. Slicing:
```Python
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1
```

### 1.4. Tensor & Numpy conversion
```Python
#From Torch to Numpy
a = torch.ones(5)
b = a.numpy()
print(f"From T to N: {type(a)} > {type(b)}") #<class 'torch.Tensor'> <class 'numpy.ndarray'>

#From Numpy to Torch
c = np.ones(5)
d = torch.from_numpy(c)
print(f"From N to T: {type(c)} > {type(d)}") #<class 'numpy.ndarray'> > <class 'torch.Tensor'>
```

### 1.5. Move Tensor from CPU to GPU
```Python
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    #=== From CPU to GPU ===
    #Method 1: directly create a tensor on GPU
    x = torch.ones(5, device = device) 
    #Method 2: just use strings ``.to("cuda")``
    y = torch.ones(5)
    y.to(device)

    #=== From GPU to CPU ===
    z = x + y #where x & y is in GPU
    z = z.to("cpu")
```

### 1.6. Require Gradient
```Python
x = torch.ones(5, requires_grad = True)
print(x) #tensor([1., 1., 1., 1., 1.], requires_grad=True)
```

In [14]:
import torch
import numpy as np

## Rand

In [3]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [5]:
z = x+y
z

tensor([[0.8182, 1.0984],
        [0.4727, 1.2381]])

In [8]:
y.add_(x)

tensor([[0.8835, 1.4329],
        [1.2530, 2.8857]])

In [10]:
y[0,1].item()

1.432852029800415

## Tensor & Numpy conversion

In [18]:
#From Torch to Numpy
a = torch.ones(5)
b = a.numpy()
print(f"From T to N: {type(a)} > {type(b)}") #<class 'torch.Tensor'> <class 'numpy.ndarray'>

#From Numpy to Torch
c = np.ones(5)
d = torch.from_numpy(c)
print(f"From N to T: {type(c)} > {type(d)}") #<class 'numpy.ndarray'> > <class 'torch.Tensor'>


From T to N: <class 'torch.Tensor'> > <class 'numpy.ndarray'>
From N to T: <class 'numpy.ndarray'> > <class 'torch.Tensor'>


In [19]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
