# 2. Gradient Calculation With Autograd

In [1]:
import torch


In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.6274, -1.3385,  0.3356], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([2.6274, 0.6615, 2.3356], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2 
print(z)

tensor([13.8065,  0.8752, 10.9103], grad_fn=<MulBackward0>)


In [11]:
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) #dz/dx
x.grad

tensor([8.0574, 4.4102, 6.2377])

In [12]:
# -------------
# Stop a tensor from tracking history:
# For example during our training loop when we want to update our weights
# then this update operation should not be part of the gradient computation
# - x.requires_grad_(False)
# - x.detach()
# - wrap in 'with torch.no_grad():'
print(x)
x.requires_grad_(False)
print(x)

tensor([ 0.6274, -1.3385,  0.3356], requires_grad=True)
tensor([ 0.6274, -1.3385,  0.3356])


In [13]:
x.requires_grad_(True)
print(x)
y = x.detach() #Remove requires_grad from x & assign to y
print(y)

tensor([ 0.6274, -1.3385,  0.3356], requires_grad=True)
tensor([ 0.6274, -1.3385,  0.3356])


In [14]:
with torch.no_grad():
    y = x + 2
    print(y) #y not have: requires_grad=True

tensor([2.6274, 0.6615, 2.3356])


In [19]:
weigths = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weigths*3).sum()

    model_output.backward()
    print(weigths.grad)

    #Need 
    weigths.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
